name: ZAP-Test

on:
  push: 
    branches: [ master ]

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python 3.7.10
        uses: actions/setup-python@v1
        with: 
          python-version: 3.7.15
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
      - name: Build Image
        run: docker build -t vulnerable-app .
      - name: Run Docker Container
        run: docker run -d -p 5050:5050 vulnerable-app
      - name: Build Image ZAP
        run: docker pull ictu/zap2docker-weekly
      - name: Run Docker Container ZAP
        run: |
          docker run --rm -v /tmp:/zap/wrk -t ictu/zap2docker-weekly zap-baseline.py -I -j -t http://localhost:5050/ -r testreport.html --hook=/zap/auth_hook.py -z "auth.loginurl=http://localhost:5050/login auth.username="admin" auth.password="admin123""
          echo "sukses"
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /tmp/testreport.html
